package librariesapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/libraries"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            AllClusterStatuses(ctx context.Context) (result libraries.AllClusterStatusesResult, err error)
            ClusterStatus(ctx context.Context, body libraries.ClusterStatusAttributes) (result libraries.ClusterStatusResult, err error)
            Install(ctx context.Context, body libraries.InstallAttributes) (result autorest.Response, err error)
            Uninstall(ctx context.Context, body libraries.InstallAttributes) (result autorest.Response, err error)
        }

        var _ BaseClientAPI = (*libraries.BaseClient)(nil)
