package libraries

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)

// The package's fully qualified name.
const fqdn = "github.com/innovationnorway/go-databricks/libraries"

        // Status enumerates the values for status.
    type Status string

    const (
                // FAILED ...
        FAILED Status = "FAILED"
                // INSTALLED ...
        INSTALLED Status = "INSTALLED"
                // INSTALLING ...
        INSTALLING Status = "INSTALLING"
                // PENDING ...
        PENDING Status = "PENDING"
                // RESOLVING ...
        RESOLVING Status = "RESOLVING"
                // UNINSTALLONRESTART ...
        UNINSTALLONRESTART Status = "UNINSTALL_ON_RESTART"
            )
    // PossibleStatusValues returns an array of possible values for the Status const type.
    func PossibleStatusValues() []Status {
        return []Status{FAILED,INSTALLED,INSTALLING,PENDING,RESOLVING,UNINSTALLONRESTART}
    }

            // AllClusterStatusesResult ...
            type AllClusterStatusesResult struct {
            autorest.Response `json:"-"`
            Statuses *[]ClusterLibraryStatuses `json:"statuses,omitempty"`
            }

            // ClusterLibraryStatuses ...
            type ClusterLibraryStatuses struct {
            ClusterID *string `json:"cluster_id,omitempty"`
            Scopes *[]LibraryFullStatus `json:"scopes,omitempty"`
            }

            // ClusterStatusAttributes ...
            type ClusterStatusAttributes struct {
            ClusterID *string `json:"cluster_id,omitempty"`
            }

            // ClusterStatusResult ...
            type ClusterStatusResult struct {
            autorest.Response `json:"-"`
            ClusterID *string `json:"cluster_id,omitempty"`
            LibraryStatuses *[]LibraryFullStatus `json:"library_statuses,omitempty"`
            }

            // InstallAttributes ...
            type InstallAttributes struct {
            ClusterID *string `json:"cluster_id,omitempty"`
            LibrariesProperty *[]Library `json:"libraries,omitempty"`
            }

            // Library ...
            type Library struct {
            Jar *string `json:"jar,omitempty"`
            Egg *string `json:"egg,omitempty"`
            Whl *string `json:"whl,omitempty"`
            Pypi *PythonPyPiLibrary `json:"pypi,omitempty"`
            Maven *MavenLibrary `json:"maven,omitempty"`
            Cran *RCranLibrary `json:"cran,omitempty"`
            }

            // LibraryFullStatus ...
            type LibraryFullStatus struct {
            Library *Library `json:"library,omitempty"`
            // Status - Possible values include: 'PENDING', 'RESOLVING', 'INSTALLING', 'INSTALLED', 'FAILED', 'UNINSTALLONRESTART'
            Status Status `json:"status,omitempty"`
            Messages *[]string `json:"messages,omitempty"`
            IsLibraryForAllClusters *bool `json:"is_library_for_all_clusters,omitempty"`
            }

            // MavenLibrary ...
            type MavenLibrary struct {
            Coordinates *string `json:"coordinates,omitempty"`
            Repo *string `json:"repo,omitempty"`
            Exclusions *[]string `json:"exclusions,omitempty"`
            }

            // PythonPyPiLibrary ...
            type PythonPyPiLibrary struct {
            Package *string `json:"package,omitempty"`
            Repo *string `json:"repo,omitempty"`
            }

            // RCranLibrary ...
            type RCranLibrary struct {
            Package *string `json:"package,omitempty"`
            Repo *string `json:"repo,omitempty"`
            }

