package jobsapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/jobs"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            Create(ctx context.Context, body jobs.CreateAttributes) (result jobs.CreateResult, err error)
            List(ctx context.Context) (result jobs.ListResult, err error)
        }

        var _ BaseClientAPI = (*jobs.BaseClient)(nil)
