package jobsapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/jobs"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            List(ctx context.Context, body jobs.Job) (result autorest.Response, err error)
        }

        var _ BaseClientAPI = (*jobs.BaseClient)(nil)
